### ISSUE TITLE
Setting debug = false causes error, path not found

### ISSUE THREAD

**Issue by spiliot** [cakephp/app#43]
I don't think this is a cake core bug

Setup: 
- Follow instructions for manual installation in `/var/www/test`
- Copy `App/Config/app.default.php` to `app.php`

Visiting `localhost/test` works fine.

Setting `debug => false` in `app.php` causes

```
Not Found
Error: The requested address '/test/' was not found on this server.
```

**Comment by tripatabhishek** [comment]
A very simple solution. 
1. Go to routes.php under config 
2. change this line 
     $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']); 
      to 
     $routes->connect('/', ['controller' => 'yourdesiredcontroller', 'action' => 'yourdesired action']); 
      and that's all.. 
      enjoy........

**Comment by haulsoft** [comment]
In Cakephp 3.0, comment out these lines in src/Template/Pages/home.ctp:
// if (!Configure::read('debug')):
//     throw new NotFoundException();
// endif;

**Comment by kings360** [comment]
I have changed the controller in the route file it works if debug is set as true , but if debug is set as false again it shows error
Error: The requested address '/' was not found on this server.

**Comment by epixilog** [comment]
Well I guess this is so much simple to do such a long conversation : 

On the home.ctp file you have : 

if (!Configure::read('debug')):
    throw new NotFoundException();
endif;

So when you put debug on false (on app.php file) your view throw this exception. So even delete or comment those lines to not have your sweet error page :smile: 
Also your exception isn't supposed to throw too many details as you put debug at false (so you're supposed to be on production)

Hai!

**Comment by clthck** [comment]
@ADmad , @haulsoft , @epixilog  thnx guys. I tried to figure it out a whole day. this is so simple and maybe a stupid issue.

**Comment by isaacrajaei** [comment]
@haulsoft If by getting read of these lines problem solves then why throw new NotFoundException() is there?
In that case you don't need to even input "use Cake\Network\Exception\NotFoundException;" in the view.

@ionas Kindly can you share with us how could you manage this error. (Obviously not by commenting  the scrips)

**Comment by ADmad** [comment]
@isaacrajaei The default homepage shows potentially sensitive environment info that's why it shouldn't be visible in production (that is with debug off), hence the exception. You are supposed to replace it with your own content. The [error message](https://github.com/cakephp/app/blob/master/src/Template/Pages/home.ctp#L24) has already been updated to indicate that.

**Comment by ashishonmobile** [comment]
I am also facing the same problem. running cakephp v3 in Ampps 3.6 , the debug mode was working fine for ampps version 3.5 but it is not working for ampps v3.6 and right now i am investigating the issue. I tried all above method but no luck. because error.log file is not having any content after error :(
