### ISSUE TITLE
Output vendor/cakephp/cakephp/VERSION.txt on default home.ctp (when debug on)

### ISSUE THREAD

**Issue by inoas** [cakephp/app#471]
Is this a good idea?

If it is, what to do about the big comment block on-top? regexp remove? or just remove and keep the number?

**Comment by antograssiot** [comment]
why would you get this information from VERSION.txt since there is already a `Configure::version()`function ?

I don't see much point in adding this to the home that is basically destroyed after 2 minutes.
Also this information is already present in the Environment panel of DebugKit.

If I were to added somewhere personally, I could rather make it more obvious in the debugkit panel or toolbar directly but that's just my two cents.

**Comment by dereuromark** [comment]
In the 2nd Environment tab it should be highlighted at the top :) But other than that it should be already quite clear.

**Comment by markstory** [comment]
I'm pretty sure the CakePHP version is _already_ in the DebugKit environment tab.

**Comment by dereuromark** [comment]
Resolved with https://github.com/cakephp/app/pull/479/files#diff-02f0cdcc6463c46cd3dcbf7ee8d639a5R29 being merged.
