### ISSUE TITLE
PHPStan: missing composer/composer package

### ISSUE THREAD

**Issue by anvyst** [cakephp/app#650]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.6.5.

### What you did

We're using `cakephp/app` as part of [project-template-cakephp](https://github.com/QoboLtd/project-template-cakephp) within our infrastructure.

### What happened

Running `phpstan analyse` complains on missing interfaces within the code, like:
```
Call to method getIO() on an unknown class Composer\Script\Event.
Call to method write() on an unknown class Composer\IO\IOInterface.
```
Errors come from `src/Console/Installer.php`.

Reference issue  from our side [#722](https://github.com/QoboLtd/project-template-cakephp/issues/722).

It comes from the fact that `composer/composer` is a dependency of `cakephp/debug_kit` package, that we don't use.

### What you expected to happen

Could you include `composer/composer` package dependency separately from `cakephp/debug_kit`, 
so we could use it without installing `cakephp/debug_kit`?

**Comment by ADmad** [comment]
The error has nothing to do with debugkit. `src/Console/Installer.php` is setup to run as post install script in composer.json.

The fact the `composer/composer` is not set as a dependency is what's causing phpstan to complain since it can't find those classes.

Just create a phpstan.neon config file in your app and ignore `Installer.php`.
